version: '3'

services:
    jenkins:
        privileged: true
        build: .
        volumes:
            - ./my_marvin.yml:/var/jenkins_casc.yml
        ports:
            - "8080:8080"
        environment:
            USER_CHOCOLATEEN_PASSWORD: "test"
            USER_VAUGIE_G_PASSWORD: "test"
            USER_I_DONT_KNOW_PASSWORD: "test"
            USER_NASSO_PASSWORD: "test"